id: P94558C35
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni
  language: bo
  description: 'Texts by and about Buddha Śākyamuni (shākya thub pa):'
  volume:
    71211dd13042499a8c2ff37197f8a2c7:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Guru Yoga
    daa76c71517243c7ade1659343289f04:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Guru Yoga
    4aed769c622f4e8da1be2aaec8f2c5d2:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Praise
    a78ec77e839d4181a71f70fa46fc5767:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    d1c1309bc46e45afbf2965de0af99089:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    b50be847816743b587f0062eb6f13a44:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    f8ae8b28faa14c6b881eba6ae125a5a0:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    bdffe92101f547e499221e830b06a3d9:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
    086cad0d2b1846068c588ab05f80bf41:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
created_at: '2022-03-01T02:12:34.858643'
last_modified_at: '2022-03-01T02:12:34.858645'
statistics:
  total_words: 5769
  total_non_words: 466
quality:
  non_words_ratio: 0.08
